sudo: false
dist: xenial
language: python
install:
  - pip install tox

matrix:
  include:
    - python: '3.6'
      env: TOXENV=py36-coveralls
    - python: '3.7'
      env: TOXENV=py37-coveralls-flake8
    - python: '3.8'
      env: TOXENV=py38-coveralls
    - python: '3.9'
      env: TOXENV=py39-coveralls

script: tox

cache:
  directories:
    - $HOME/.cache/pip

notifications:
  irc:
    channels:
    - irc.freenode.org#cs-york-dev
    skip_join: true
    use_notice: true
