language: python
python:
    - "2.7"
install: "pip install -r requirements-dev.txt --use-mirrors"
script:
#    - flake8 --exclude=plugins_broken csbot
    - trial csbot
notifications:
    irc:
        channels:
            - "irc.freenode.org#cs-york-dev"
        skip_join: true
